<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>openimaj-core-libs</artifactId>
    <groupId>org.openimaj</groupId>
    <version>1.5.0-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>
  
  <artifactId>core-math</artifactId>
  <name>The OpenIMAJ Core Math Library</name>
  <inceptionYear>2011</inceptionYear>
  <description>
		Mathematical implementations including geometric, matrix and statistical operators. 
  </description>
  
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <commons-math.version>3.6.1</commons-math.version>
    <gov-sandia.version>3.3.0</gov-sandia.version><!-- more recent version available -->
    <jama.version>1.0.3</jama.version>
    <jgrapht-core.version>1.5.2</jgrapht-core.version>
    <jmatio.version>1.5</jmatio.version>
    <junit.version>4.13.2</junit.version>
    <la4j.version>0.7.0</la4j.version>
    <mtj.version>1.0.4</mtj.version>
    <xstream.version>1.4.21</xstream.version>
  </properties>
  
  <dependencies>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>core</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>gov.nist.math</groupId>
      <artifactId>jama</artifactId>
      <version>${jama.version}</version>
    </dependency>
    <dependency>
	  <groupId>dev.secondsun</groupId>
	  <artifactId>org.la4j.la4j</artifactId>
	  <version>${la4j.version}</version>
	</dependency>
    <dependency>
      <groupId>com.googlecode.matrix-toolkits-java</groupId>
      <artifactId>mtj</artifactId>
      <version>${mtj.version}</version>
    </dependency>
    <dependency>
      <groupId>net.jafama</groupId>
      <artifactId>jafama</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-core</artifactId>
      <version>${jgrapht-core.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-opt</artifactId>
      <version>${jgrapht-core.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.openimaj</groupId>
      <artifactId>MatrixLib</artifactId>
    </dependency>
    <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-common-core</artifactId>
      <version>${gov-sandia.version}</version>
			<exclusions>
				<exclusion>
					<groupId>com.thoughtworks.xstream</groupId>
					<artifactId>xstream</artifactId>
				</exclusion>
			</exclusions>
    </dependency>
	<dependency>
		<groupId>com.thoughtworks.xstream</groupId>
		<artifactId>xstream</artifactId>
		<version>${xstream.version}</version>
	</dependency>
    <!-- <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-common-data</artifactId>
      <version>3.3.0</version>
    </dependency> -->
    <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-learning-core</artifactId>
      <version>${gov-sandia.version}</version>
    </dependency>
    <!-- <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-text-core</artifactId>
      <version>3.3.0</version>
    </dependency>
    <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-framework-core</artifactId>
      <version>3.3.0</version>
    </dependency>
    <dependency>
      <groupId>gov.sandia.foundry</groupId>
      <artifactId>gov-sandia-cognition-framework-learning</artifactId>
      <version>3.3.0</version>
    </dependency> -->
    <dependency>
      <groupId>org.tallison</groupId>
      <artifactId>jmatio</artifactId>
      <version>${jmatio.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>${commons-math.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  
  <build>
    <plugins>
      <plugin>
		<groupId>com.mycila</groupId>
		<artifactId>license-maven-plugin</artifactId>
        <configuration>
          <header>src/etc/header.txt</header>
          <strictCheck>true</strictCheck>
          <properties>
            <year>${project.inceptionYear}</year>
          </properties>
          <excludes>
            <exclude>AUTHORS</exclude>
            <exclude>COPYING</exclude>
          </excludes>
          <mapping>
            <jtemp>JAVADOC_STYLE</jtemp>
          </mapping>
          <useDefaultMapping>true</useDefaultMapping>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
