<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <parent>
    <artifactId>openimaj-core-libs</artifactId>
    <groupId>org.openimaj</groupId>
    <version>1.5.0-SNAPSHOT</version>
	<relativePath>../</relativePath>
  </parent>
  
  <artifactId>core-aop-support</artifactId>
  <packaging>jar</packaging>
  <name>Core Aspect Oriented Programming Support</name>
	<inceptionYear>2011</inceptionYear>
  <description>
  	Core support for Aspect Oriented Programming and Bytecode manipulation as used in core-citation
  	and core-experiment
  </description>
  
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <javassist.version>3.30.2-GA</javassist.version>
    <junit.version>4.13.2</junit.version>
    <log4j.version>2.25.0</log4j.version>
  </properties>
  
  <dependencies>
    <dependency>
      <groupId>org.javassist</groupId>
      <artifactId>javassist</artifactId>
      <version>${javassist.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>${log4j.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>${log4j.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
		<groupId>com.mycila</groupId>
		<artifactId>license-maven-plugin</artifactId>
        <configuration>
          <header>src/etc/header.txt</header>
          <strictCheck>true</strictCheck>
          <properties>
            <year>${project.inceptionYear}</year>
          </properties>
          <excludes>
            <exclude>AUTHORS</exclude>
            <exclude>COPYING</exclude>
          </excludes>
          <mapping>
            <jtemp>JAVADOC_STYLE</jtemp>
          </mapping>
          <useDefaultMapping>true</useDefaultMapping>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <proc>none</proc>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
