<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <parent>
    <artifactId>openimaj</artifactId>
    <groupId>org.openimaj</groupId>
    <version>1.5.0-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>
  
  <artifactId>test-resources</artifactId>
  <name>OpenIMAJ Unit Test Resources</name>
  <description>
	Resources for running OpenIMAJ JUnit tests.
  </description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.version>4.13.2</junit.version>
  </properties>
  
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
		<groupId>com.mycila</groupId>
		<artifactId>license-maven-plugin</artifactId>
        <configuration>
          <header>src/etc/header.txt</header>
          <strictCheck>true</strictCheck>
          <properties>
            <year>${project.inceptionYear}</year>
          </properties>
          <excludes>
            <exclude>AUTHORS</exclude>
            <exclude>COPYING</exclude>
            <exclude>**/*.voc</exclude>
            <exclude>**/*.key</exclude>
            <exclude>**/*.bkey</exclude>
            <exclude>**/*.bin</exclude>
            <exclude>**/*.JPG</exclude>
            <exclude>**/*.haraff</exclude>
            <exclude>**/*.jpg</exclude>
            <exclude>**/*.png</exclude>
            <exclude>**/*.ppm</exclude>
            <exclude>**/*.avi</exclude>
            <exclude>**/H1*</exclude>
            <exclude>**/*.jpeg</exclude>
            <exclude>**/*.json</exclude>
            <exclude>**/*.txt</exclude>
          </excludes>
          <mapping>
            <jtemp>JAVADOC_STYLE</jtemp>
          </mapping>
          <useDefaultMapping>true</useDefaultMapping>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
